### ISSUE TITLE
Rate of change constraint supported?

### ISSUE THREAD

**Issue by wenlzhang** [meco-group/rockit#1]
Is there an easy way to include rate of change constraint on control, with something like `-1 <= du <= 1` rather than defining a new state variable?

**Comment by jgillis** [comment]
A wat to do it with finite differences is planned.
What is now available is:

```
u = ocp.control(order=1)
-1 <= ocp.der(u) <= 1
```

**Comment by wenlzhang** [comment]
I tried to add the rate of change constraint as suggested with the following definition:
```
u = ocp.control(order=1)
ocp.subject_to(-1 <= (ocp.der(u) <= 1))
```

However, at certain time point where the control is about to cross zero, the control would change from -1 to 1, which violates the constraint. At other time points, it seems to work.

Do I need some other definitions?

**Comment by jgillis** [comment]
After private discussion, it turns out OP was using ocp.x and ocp.u instead of self-created states and controls.
ocp.x and ocp.u are for internal usage; their interpretation is nontrivial in the case of `order>0`.

See also https://gitlab.kuleuven.be/meco-software/rockit/-/issues/131
