### ISSUE TITLE
Algebraic constraint of the form g(x,z,u) supported?

### ISSUE THREAD

**Issue by wenlzhang** [meco-group/rockit#2]
From the DAE example in the repository, it can be seen that algebraic constraint of the form `g(x,z) = 0` is supported. Is it also possible to use `g(x,z,u) = 0`?

**Comment by jgillis** [comment]
It'd be a bug if it wasn't..

**Comment by wenlzhang** [comment]
My bad... Preliminary tests show that applying algebraic constraint of the form `g(x,z,u) = 0` can give some results. I will do more tests to further validate if the results are desired or not. Closing it for now.
