### ISSUE TITLE
Soft constraints and slack variables supported?

### ISSUE THREAD

**Issue by wenlzhang** [meco-group/rockit#3]
With the latest version of rockit, i.e. version 0.1.20, are soft constraints and slack variables supported? If not, are there any suggested way of applying soft constraints? How to define slack variables and how to apply soft constraints?

In `stage.py`, I found the following types of variables/parameters:
```python
self.states = HashList()
self.qstates = HashList()
self.controls = HashList()
self.algebraics = HashList()
self.parameters = defaultdict(HashList)
self.variables = defaultdict(HashList)
```

Also found the following issue that might be related to this:
https://gitlab.kuleuven.be/meco-software/rockit/-/issues/129

**Comment by jgillis** [comment]
The issue is about a compact syntax; you can already get soft constraints with a bit of extra work:

For example, to make "g(x)<=0" soft:
```python
slack=ocp.variable(grid='control')
ocp.subject_to(slack>=0)
ocp.add_objective(slack**2)
ocp.subject_to(g(x)<=slack)
```

**Comment by wenlzhang** [comment]
Thanks. The suggested method worked for me.

Just to be clear about the way of defining the cost function term corresponding to the slack variable, maybe it can be modified into the following form:
```python
ocp.add_objective(ocp.integral(slack**2, grid='control'))
```
Correct me if I am wrong about this. Otherwise, the issue can be closed.

**Comment by jgillis** [comment]
Ah sorry, you are right
